#!/bin/bash
#chmod -x filename

# Build and compile the visualizer library
cd _BUILD
rm -r projects/player
#rm projects/tester_2/tester_2
#rm CMakeCache.txt cmake_install.cmake libMachLib.a Makefile
#rm -r CMakeFiles

cmake -G"Unix Makefiles" ..
make

#cd projects/lighting && ./lighting
cd projects/player && ./player
